language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
env:
  global:
    - HF_HOME=${HOME}/.huggingface
cache:
  pip: true
  directories:
    - ${HF_HOME}
install: pip install tox-travis
script: tox -r