language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
env:
  global:
    - HF_HOME=${HOME}/.cache/huggingface
    - HF_DATASETS_CACHE=${HF_HOME}/datasets
cache:
  pip: true
  directories:
    - ${HF_HOME}
install:
  - mkdir -pv ${HF_DATASETS_CACHE}
  - pip install tox-travis
script: tox -r