language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
cache: pip
jobs:
  include:
    - name: Tests
      install: pip install tox-travis
      script: tox -r
    # Make sure all dependencies can be resolved and installed
    - name: Resolve & Install Dependencies
      install: pip install .[all]
      script: exit 0