language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
cache: pip
#install: pip install --use-feature=in-tree-build .
install: pip install tox-travis
script: tox -r --cov oneqa tests/ --cov-config .coveragerc