name: SphinxDoc Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies (docs/requirements.txt)
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install 'torch~=1.11.0' --extra-index-url https://download.pytorch.org/whl/cu113
        if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
    - name: SphinxDoc Make HTML
      run: |
        cd docs
        make html -e SPHINXOPTS='--keep-going --no-color -w "log_file"'   
    # - name: Upload artifacts (docs/_build/)
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: html-docs
    #     path: docs/_build/
    - name: Upload artifacts (docs/log_file)
      uses: actions/upload-artifact@v3
      with:
        name: html-docs-log_file
        path: docs/log_file
    - name: Deploy Documentation (gh-pages branch)
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/issue279-redesign-doc'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
        commit_message: -automatic commit- Sphinx Doc Build